/*
=> make it simple

CREATE TABLE PERSON
(
    ID   BIGINT IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX UNIQUE_PERSON ON PERSON (NAME);*/

CREATE TABLE ACCOUNT
(
    ID             BIGINT IDENTITY NOT NULL PRIMARY KEY,
    NAME           VARCHAR(100)   NOT NULL,
    ACCOUNT_NUMBER VARCHAR(8)     NOT NULL,
    SORT_CODE      VARCHAR(6)     NOT NULL,
    BALANCE        NUMERIC(16, 2) NOT NULL
    /*,PERSON_ID      BIGINT         NOT NULL*/
);

/*ALTER TABLE ACCOUNT
    ADD FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID);*/

CREATE UNIQUE INDEX UNIQUE_ACCOUNT ON ACCOUNT
    (ACCOUNT_NUMBER, SORT_CODE);

CREATE TABLE TRANSACTION
(
    ID         BIGINT IDENTITY NOT NULL PRIMARY KEY,
    ACCOUNT_ID BIGINT         NOT NULL,
    AMOUNT     NUMERIC(10, 2) NOT NULL,
    TYPE       CHAR(1)        NOT NULL /*D or C*/
);

ALTER TABLE TRANSACTION
    ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID);